version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - file-storage
      - file-analysis
    environment:
      - FILE_STORAGE_SERVICE_URL=http://file-storage:8081
      - FILE_ANALYSIS_SERVICE_URL=http://file-analysis:8082

  file-storage:
    build: ./file-storage
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/file_storage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  file-analysis:
    build: ./file-analysis
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - file-storage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/file_analysis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FILE_STORAGE_SERVICE_URL=http://file-storage:8081

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=file_storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: